repos:
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.6.9
    hooks:
      - id: ruff
        types_or:
          - python
          - pyi
        args:
          - '--unsafe-fixes'
          - '--fix'
        files: ^(kedung/|examples/|tests/).*\.py$
      - id: ruff-format
        types_or:
          - python
          - pyi
        files: ^(kedung/|examples/|tests/).*\.py$
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v1.11.2
    hooks:
      - id: mypy
        files: ^(kedung/|examples/|tests/).*\.py$
